languages:
  Ruby: true
  JavaScript: true

engines:
  markdownlint:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true

exclude_paths:
  - "log/"
  - "public/"
  - "tmp/"
