AllCops:
  Exclude:
    - bin/**/*
    - db/**/*

Documentation:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

UnneededPercentQ:
  Enabled: false

AbcSize:
  Enabled: false

ClassLength:
  Enabled: false

Rails:
  Enabled: true
