language: ruby

rvm:
  - 2.3.1

script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - CODECLIMATE_REPO_TOKEN=981eb9d81e6c62c5bd09240ee6f082f247dc129f29b9a0f66f15476c7d6a5fb3 bundle exec rspec spec

services:
  - postgresql
  - redis-server

addons:
  postgresql: "9.4"
  code_climate:
    repo_token: 981eb9d81e6c62c5bd09240ee6f082f247dc129f29b9a0f66f15476c7d6a5fb3
