language: ruby

rvm:
  - 2.3.1

script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec spec

services:
  - postgresql
  - redis-server

addons:
  postgresql: "9.4"
