files: ["**/*.js"]
exclude_paths: []
options:
  boss:       true
  browser:    true
  curly:      true
  eqeqeq:     true
  eqnull:     true
  expr:       true
  immed:      true
  indent:     2
  latedef:    true
  newcap:     true
  noarg:      true
  sub:        true
  trailing:   true
  undef:      true
  unused:     true
  exported:
    Util:     true
  globals:
    angular:  true
    Util:     true
    Chartist: true
